[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "biblio"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "pandoc>=2.4",
    "pikepdf>=9.4.2",
    "requests>=2.32.3",
]

